services:
  - type: web
    name: tongarm
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MINI_APP_URL
        value: https://tongarm.onrender.com/
